"""Replace the two-tier-loss-contract cell in lstm-baseline.ipynb with inlined losses.py.

How to Run: python scratch/inline_losses_lstm.py
Expected Output: lstm-baseline.ipynb updated with inlined loss module.
"""
import json
from pathlib import Path

NOTEBOOK = Path(__file__).resolve().parent.parent / "notebooks" / "lstm-baseline.ipynb"

# New cell source: full losses.py inlined directly, no try/except import.
NEW_SOURCE = [
    "# ── Shared two-tier loss, calibration, and probability metrics ──────────────\n",
    "# Inlined from src/models/losses.py for standalone execution (e.g. Kaggle).\n",
    "# The benchmark protocol uses plain multiclass negative log-likelihood (NLL).\n",
    "# The ordinal ablation adds a normalized squared CDF distance (EMD) without\n",
    "# changing the model output shape or using CORAL/CORN.\n",
    "\n",
    "from __future__ import annotations\n",
    "\n",
    "from dataclasses import dataclass\n",
    "from typing import Any, Iterable\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from scipy.optimize import minimize_scalar\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score,\n",
    "    cohen_kappa_score,\n",
    "    f1_score,\n",
    "    roc_auc_score,\n",
    ")\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import label_binarize\n",
    "\n",
    "BENCHMARK_PROTOCOL = \"benchmark_ce\"\n",
    "ORDINAL_PROTOCOL = \"ordinal_ce_emd\"\n",
    "SUPPORTED_PROTOCOLS = (BENCHMARK_PROTOCOL, ORDINAL_PROTOCOL)\n",
    "DEFAULT_ORDINAL_LAMBDA = 0.10\n",
    "DEFAULT_LABEL_ORDER = (\"Distressed\", \"HY\", \"IG\")\n",
    "_EPS = 1e-12\n",
    "\n",
    "# Papermill-injectable parameters.\n",
    "LOSS_PROTOCOL = str(globals().get(\"LOSS_PROTOCOL\", \"benchmark_ce\")).strip().lower()\n",
    "ORDINAL_LAMBDA = float(globals().get(\"ORDINAL_LAMBDA\", 0.10))\n",
    "TARGET_ORDERED_LABELS = [\"Distressed\", \"HY\", \"IG\"]\n",
    "\n",
    "\n",
    "def normalize_protocol(protocol: str) -> str:\n",
    "    \"\"\"Validate and normalize a two-tier loss protocol name.\"\"\"\n",
    "    normalized = str(protocol).strip().lower()\n",
    "    if normalized not in SUPPORTED_PROTOCOLS:\n",
    "        raise ValueError(\n",
    "            f\"Unsupported loss protocol {protocol!r}; expected one of \"\n",
    "            f\"{SUPPORTED_PROTOCOLS}.\"\n",
    "        )\n",
    "    return normalized\n",
    "\n",
    "\n",
    "def _normalize_probabilities(probabilities: Any) -> np.ndarray:\n",
    "    probs = np.asarray(probabilities, dtype=np.float64)\n",
    "    if probs.ndim != 2 or probs.shape[1] < 2:\n",
    "        raise ValueError(\"probabilities must have shape (n_samples, n_classes>=2)\")\n",
    "    if not np.isfinite(probs).all():\n",
    "        raise ValueError(\"probabilities contain NaN or infinite values\")\n",
    "    probs = np.clip(probs, _EPS, None)\n",
    "    row_sums = probs.sum(axis=1, keepdims=True)\n",
    "    if np.any(row_sums <= 0.0):\n",
    "        raise ValueError(\"each probability row must have a positive sum\")\n",
    "    return probs / row_sums\n",
    "\n",
    "\n",
    "def _validate_targets(targets: Any, n_samples: int, n_classes: int) -> np.ndarray:\n",
    "    y_true = np.asarray(targets, dtype=np.int64).reshape(-1)\n",
    "    if len(y_true) != n_samples:\n",
    "        raise ValueError(\"targets length does not match probabilities\")\n",
    "    if np.any((y_true < 0) | (y_true >= n_classes)):\n",
    "        raise ValueError(\"targets contain class ids outside the probability columns\")\n",
    "    return y_true\n",
    "\n",
    "\n",
    "def numpy_nll(probabilities: Any, targets: Any) -> float:\n",
    "    \"\"\"Mean multiclass negative log-likelihood from probabilities.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    y_true = _validate_targets(targets, len(probs), probs.shape[1])\n",
    "    return float(-np.log(probs[np.arange(len(y_true)), y_true]).mean())\n",
    "\n",
    "\n",
    "def numpy_cdf_emd2(probabilities: Any, targets: Any) -> float:\n",
    "    \"\"\"Normalized squared CDF distance for ordered multiclass probabilities.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    y_true = _validate_targets(targets, len(probs), probs.shape[1])\n",
    "    target_one_hot = np.eye(probs.shape[1], dtype=np.float64)[y_true]\n",
    "    predicted_cdf = np.cumsum(probs, axis=1)[:, :-1]\n",
    "    target_cdf = np.cumsum(target_one_hot, axis=1)[:, :-1]\n",
    "    return float(np.square(predicted_cdf - target_cdf).mean())\n",
    "\n",
    "\n",
    "def numpy_objective(\n",
    "    probabilities: Any,\n",
    "    targets: Any,\n",
    "    *,\n",
    "    protocol: str = BENCHMARK_PROTOCOL,\n",
    "    ordinal_lambda: float = DEFAULT_ORDINAL_LAMBDA,\n",
    ") -> float:\n",
    "    \"\"\"Evaluate the selected two-tier objective from class probabilities.\"\"\"\n",
    "    protocol = normalize_protocol(protocol)\n",
    "    nll = numpy_nll(probabilities, targets)\n",
    "    if protocol == BENCHMARK_PROTOCOL:\n",
    "        return nll\n",
    "    return nll + float(ordinal_lambda) * numpy_cdf_emd2(probabilities, targets)\n",
    "\n",
    "\n",
    "def benchmark_ce(logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:\n",
    "    \"\"\"Plain multiclass CE used by the primary benchmark.\"\"\"\n",
    "    return F.cross_entropy(logits.float(), targets.long(), label_smoothing=0.0)\n",
    "\n",
    "\n",
    "def cdf_emd2(logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:\n",
    "    \"\"\"Differentiable normalized squared CDF distance from logits.\"\"\"\n",
    "    logits = logits.float()\n",
    "    targets = targets.long()\n",
    "    probabilities = torch.softmax(logits, dim=1)\n",
    "    target_one_hot = F.one_hot(\n",
    "        targets,\n",
    "        num_classes=probabilities.shape[1],\n",
    "    ).to(dtype=probabilities.dtype)\n",
    "    predicted_cdf = probabilities.cumsum(dim=1)[:, :-1]\n",
    "    target_cdf = target_one_hot.cumsum(dim=1)[:, :-1]\n",
    "    return (predicted_cdf - target_cdf).square().mean()\n",
    "\n",
    "\n",
    "def ordinal_ce_emd(\n",
    "    logits: torch.Tensor,\n",
    "    targets: torch.Tensor,\n",
    "    *,\n",
    "    ordinal_lambda: float = DEFAULT_ORDINAL_LAMBDA,\n",
    ") -> torch.Tensor:\n",
    "    \"\"\"CE plus normalized squared CDF-EMD for the ordinal ablation.\"\"\"\n",
    "    return benchmark_ce(logits, targets) + float(ordinal_lambda) * cdf_emd2(\n",
    "        logits,\n",
    "        targets,\n",
    "    )\n",
    "\n",
    "\n",
    "class TwoTierClassificationLoss(nn.Module):\n",
    "    \"\"\"Single loss API shared by all neural notebook baselines.\"\"\"\n",
    "\n",
    "    def __init__(\n",
    "        self,\n",
    "        protocol: str = BENCHMARK_PROTOCOL,\n",
    "        ordinal_lambda: float = DEFAULT_ORDINAL_LAMBDA,\n",
    "    ) -> None:\n",
    "        super().__init__()\n",
    "        self.protocol = normalize_protocol(protocol)\n",
    "        self.ordinal_lambda = float(ordinal_lambda)\n",
    "        if self.ordinal_lambda < 0.0:\n",
    "            raise ValueError(\"ordinal_lambda must be non-negative\")\n",
    "\n",
    "    def monitor_loss(\n",
    "        self,\n",
    "        logits: torch.Tensor,\n",
    "        targets: torch.Tensor,\n",
    "    ) -> torch.Tensor:\n",
    "        \"\"\"Always return comparable plain NLL for curves and reports.\"\"\"\n",
    "        return benchmark_ce(logits, targets)\n",
    "\n",
    "    def loss_parts(\n",
    "        self,\n",
    "        logits: torch.Tensor,\n",
    "        targets: torch.Tensor,\n",
    "        **_: Any,\n",
    "    ) -> dict[str, torch.Tensor]:\n",
    "        nll = benchmark_ce(logits, targets)\n",
    "        emd = cdf_emd2(logits, targets)\n",
    "        objective = (\n",
    "            nll\n",
    "            if self.protocol == BENCHMARK_PROTOCOL\n",
    "            else nll + self.ordinal_lambda * emd\n",
    "        )\n",
    "        return {\n",
    "            \"objective\": objective,\n",
    "            \"nll\": nll,\n",
    "            \"cdf_emd2\": emd,\n",
    "            # Compatibility aliases for existing notebook training loops.\n",
    "            \"ce_loss\": nll,\n",
    "            \"aux_loss\": objective - nll,\n",
    "        }\n",
    "\n",
    "    def forward(\n",
    "        self,\n",
    "        logits: torch.Tensor,\n",
    "        targets: torch.Tensor,\n",
    "        **_: Any,\n",
    "    ) -> torch.Tensor:\n",
    "        return self.loss_parts(logits, targets)[\"objective\"]\n",
    "\n",
    "\n",
    "def build_loss(\n",
    "    protocol: str = BENCHMARK_PROTOCOL,\n",
    "    ordinal_lambda: float = DEFAULT_ORDINAL_LAMBDA,\n",
    ") -> TwoTierClassificationLoss:\n",
    "    \"\"\"Factory used by notebook import and fallback paths.\"\"\"\n",
    "    return TwoTierClassificationLoss(\n",
    "        protocol=protocol,\n",
    "        ordinal_lambda=ordinal_lambda,\n",
    "    )\n",
    "\n",
    "\n",
    "def apply_temperature(probabilities: Any, temperature: float) -> np.ndarray:\n",
    "    \"\"\"Apply scalar temperature scaling to probabilities via log-probabilities.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    temperature = float(temperature)\n",
    "    if not np.isfinite(temperature) or temperature <= 0.0:\n",
    "        raise ValueError(\"temperature must be finite and positive\")\n",
    "    scaled_logits = np.log(probs) / temperature\n",
    "    scaled_logits -= scaled_logits.max(axis=1, keepdims=True)\n",
    "    scaled = np.exp(scaled_logits)\n",
    "    return scaled / scaled.sum(axis=1, keepdims=True)\n",
    "\n",
    "\n",
    "def fit_temperature(\n",
    "    probabilities: Any,\n",
    "    targets: Any,\n",
    "    *,\n",
    "    bounds: tuple[float, float] = (0.05, 10.0),\n",
    ") -> float:\n",
    "    \"\"\"Fit one temperature on validation probabilities by minimizing NLL.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    y_true = _validate_targets(targets, len(probs), probs.shape[1])\n",
    "    lower, upper = map(float, bounds)\n",
    "    if not 0.0 < lower < upper:\n",
    "        raise ValueError(\"temperature bounds must satisfy 0 < lower < upper\")\n",
    "    result = minimize_scalar(\n",
    "        lambda value: numpy_nll(apply_temperature(probs, value), y_true),\n",
    "        bounds=(lower, upper),\n",
    "        method=\"bounded\",\n",
    "        options={\"xatol\": 1e-6},\n",
    "    )\n",
    "    if not result.success or not np.isfinite(result.x):\n",
    "        return 1.0\n",
    "    return float(np.clip(result.x, lower, upper))\n",
    "\n",
    "\n",
    "@dataclass(frozen=True)\n",
    "class TemperatureCalibrationResult:\n",
    "    \"\"\"Cross-fitted validation and final test calibration output.\"\"\"\n",
    "\n",
    "    validation_probabilities: np.ndarray\n",
    "    test_probabilities: np.ndarray\n",
    "    temperature: float\n",
    "    fold_temperatures: tuple[float, ...]\n",
    "    n_splits: int\n",
    "\n",
    "\n",
    "def cross_fit_temperature_scaling(\n",
    "    validation_probabilities: Any,\n",
    "    validation_targets: Any,\n",
    "    test_probabilities: Any,\n",
    "    *,\n",
    "    max_splits: int = 5,\n",
    "    seed: int = 42,\n",
    ") -> TemperatureCalibrationResult:\n",
    "    \"\"\"Cross-fit validation calibration and fit one final validation temperature.\"\"\"\n",
    "    val_probs = _normalize_probabilities(validation_probabilities)\n",
    "    test_probs = _normalize_probabilities(test_probabilities)\n",
    "    if val_probs.shape[1] != test_probs.shape[1]:\n",
    "        raise ValueError(\"validation and test probabilities need equal class counts\")\n",
    "    y_val = _validate_targets(validation_targets, len(val_probs), val_probs.shape[1])\n",
    "\n",
    "    class_counts = np.bincount(y_val, minlength=val_probs.shape[1])\n",
    "    positive_counts = class_counts[class_counts > 0]\n",
    "    n_splits = min(int(max_splits), int(positive_counts.min())) if len(positive_counts) else 0\n",
    "    calibrated_val = np.empty_like(val_probs)\n",
    "    fold_temperatures: list[float] = []\n",
    "\n",
    "    if n_splits >= 2:\n",
    "        splitter = StratifiedKFold(\n",
    "            n_splits=n_splits,\n",
    "            shuffle=True,\n",
    "            random_state=int(seed),\n",
    "        )\n",
    "        for fit_idx, holdout_idx in splitter.split(val_probs, y_val):\n",
    "            temperature = fit_temperature(val_probs[fit_idx], y_val[fit_idx])\n",
    "            calibrated_val[holdout_idx] = apply_temperature(\n",
    "                val_probs[holdout_idx],\n",
    "                temperature,\n",
    "            )\n",
    "            fold_temperatures.append(temperature)\n",
    "    else:\n",
    "        n_splits = 1\n",
    "        temperature = fit_temperature(val_probs, y_val)\n",
    "        calibrated_val[:] = apply_temperature(val_probs, temperature)\n",
    "        fold_temperatures.append(temperature)\n",
    "\n",
    "    final_temperature = fit_temperature(val_probs, y_val)\n",
    "    calibrated_test = apply_temperature(test_probs, final_temperature)\n",
    "    return TemperatureCalibrationResult(\n",
    "        validation_probabilities=calibrated_val,\n",
    "        test_probabilities=calibrated_test,\n",
    "        temperature=final_temperature,\n",
    "        fold_temperatures=tuple(fold_temperatures),\n",
    "        n_splits=n_splits,\n",
    "    )\n",
    "\n",
    "\n",
    "def multiclass_brier_score(probabilities: Any, targets: Any) -> float:\n",
    "    \"\"\"Mean multiclass Brier score.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    y_true = _validate_targets(targets, len(probs), probs.shape[1])\n",
    "    target_one_hot = np.eye(probs.shape[1], dtype=np.float64)[y_true]\n",
    "    return float(np.square(probs - target_one_hot).sum(axis=1).mean())\n",
    "\n",
    "\n",
    "def expected_calibration_error(\n",
    "    probabilities: Any,\n",
    "    targets: Any,\n",
    "    *,\n",
    "    n_bins: int = 15,\n",
    ") -> float:\n",
    "    \"\"\"Top-label expected calibration error.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    y_true = _validate_targets(targets, len(probs), probs.shape[1])\n",
    "    predictions = probs.argmax(axis=1)\n",
    "    confidence = probs.max(axis=1)\n",
    "    correctness = predictions == y_true\n",
    "    edges = np.linspace(0.0, 1.0, int(n_bins) + 1)\n",
    "    ece = 0.0\n",
    "    for index in range(int(n_bins)):\n",
    "        lower, upper = edges[index], edges[index + 1]\n",
    "        mask = (\n",
    "            (confidence >= lower) & (confidence < upper)\n",
    "            if index < int(n_bins) - 1\n",
    "            else (confidence >= lower) & (confidence <= upper)\n",
    "        )\n",
    "        if mask.any():\n",
    "            ece += float(mask.mean()) * abs(\n",
    "                float(correctness[mask].mean()) - float(confidence[mask].mean())\n",
    "            )\n",
    "    return float(ece)\n",
    "\n",
    "\n",
    "def probability_report(\n",
    "    targets: Any,\n",
    "    probabilities: Any,\n",
    "    *,\n",
    "    protocol: str = BENCHMARK_PROTOCOL,\n",
    "    ordinal_lambda: float = DEFAULT_ORDINAL_LAMBDA,\n",
    "    last_y: Any | None = None,\n",
    ") -> dict[str, float | str]:\n",
    "    \"\"\"Return the common benchmark/ablation metric contract.\"\"\"\n",
    "    probs = _normalize_probabilities(probabilities)\n",
    "    y_true = _validate_targets(targets, len(probs), probs.shape[1])\n",
    "    y_pred = probs.argmax(axis=1)\n",
    "    nll = numpy_nll(probs, y_true)\n",
    "    emd = numpy_cdf_emd2(probs, y_true)\n",
    "    normalized_protocol = normalize_protocol(protocol)\n",
    "    objective = (\n",
    "        nll\n",
    "        if normalized_protocol == BENCHMARK_PROTOCOL\n",
    "        else nll + float(ordinal_lambda) * emd\n",
    "    )\n",
    "    y_bin = label_binarize(y_true, classes=np.arange(probs.shape[1]))\n",
    "    try:\n",
    "        auc = float(\n",
    "            roc_auc_score(y_bin, probs, average=\"macro\", multi_class=\"ovr\")\n",
    "        )\n",
    "    except ValueError:\n",
    "        auc = float(\"nan\")\n",
    "    report: dict[str, float | str] = {\n",
    "        \"Protocol\": normalized_protocol,\n",
    "        \"NLL\": nll,\n",
    "        \"Objective\": objective,\n",
    "        \"CDF_EMD2\": emd,\n",
    "        \"Brier\": multiclass_brier_score(probs, y_true),\n",
    "        \"ECE\": expected_calibration_error(probs, y_true),\n",
    "        \"Accuracy\": float(accuracy_score(y_true, y_pred)),\n",
    "        \"Macro_F1\": float(f1_score(y_true, y_pred, average=\"macro\", zero_division=0)),\n",
    "        \"Weighted_F1\": float(\n",
    "            f1_score(y_true, y_pred, average=\"weighted\", zero_division=0)\n",
    "        ),\n",
    "        \"QWK\": float(cohen_kappa_score(y_true, y_pred, weights=\"quadratic\")),\n",
    "        \"Ordinal_MAE\": float(np.abs(y_true - y_pred).mean()),\n",
    "        \"AUC_ROC_OVR_Macro\": auc,\n",
    "        \"AUC\": auc,\n",
    "    }\n",
    "    if last_y is None:\n",
    "        report[\"ChgAcc\"] = float(\"nan\")\n",
    "    else:\n",
    "        previous = np.asarray(last_y, dtype=np.int64).reshape(-1)\n",
    "        if len(previous) != len(y_true):\n",
    "            raise ValueError(\"last_y length does not match targets\")\n",
    "        change_mask = previous != y_true\n",
    "        report[\"ChgAcc\"] = (\n",
    "            float(accuracy_score(y_true[change_mask], y_pred[change_mask]))\n",
    "            if change_mask.any()\n",
    "            else float(\"nan\")\n",
    "        )\n",
    "    return report\n",
    "\n",
    "\n",
    "def reliability_weights_from_nll(\n",
    "    validation_targets: Any,\n",
    "    model_probabilities: Iterable[Any],\n",
    ") -> np.ndarray:\n",
    "    \"\"\"Normalize exp(-validation NLL) reliability weights across models.\"\"\"\n",
    "    losses = np.asarray(\n",
    "        [numpy_nll(probabilities, validation_targets) for probabilities in model_probabilities],\n",
    "        dtype=np.float64,\n",
    "    )\n",
    "    raw = np.exp(-(losses - losses.min()))\n",
    "    return raw / raw.sum()\n",
    "\n",
    "\n",
    "# ── Protocol validation ─────────────────────────────────────────────────────\n",
    "TWO_TIER_LOSS_SOURCE = \"inline (losses.py)\"\n",
    "if LOSS_PROTOCOL not in {BENCHMARK_PROTOCOL, ORDINAL_PROTOCOL}:\n",
    "    raise ValueError(f\"LOSS_PROTOCOL must be {BENCHMARK_PROTOCOL!r} or {ORDINAL_PROTOCOL!r}\")\n",
    "print(f\"Two-tier loss source={TWO_TIER_LOSS_SOURCE} | protocol={LOSS_PROTOCOL} | ordinal_lambda={ORDINAL_LAMBDA:.2f}\")\n",
]


def main() -> None:
    nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))

    # Find the cell by id or tag
    target_idx = None
    for idx, cell in enumerate(nb["cells"]):
        cell_id = cell.get("id", "")
        tags = cell.get("metadata", {}).get("tags", [])
        if cell_id == "two-tier-loss-contract" or "two-tier-loss-contract" in tags:
            target_idx = idx
            break

    if target_idx is None:
        raise RuntimeError("Cell 'two-tier-loss-contract' not found in notebook!")

    print(f"Found target cell at index {target_idx} (id={nb['cells'][target_idx].get('id')})")
    print(f"Old source lines: {len(nb['cells'][target_idx]['source'])}")

    # Replace source
    nb["cells"][target_idx]["source"] = NEW_SOURCE
    nb["cells"][target_idx]["outputs"] = []

    print(f"New source lines: {len(NEW_SOURCE)}")

    # Write back
    NOTEBOOK.write_text(
        json.dumps(nb, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )
    print("Done: updated", str(NOTEBOOK))


if __name__ == "__main__":
    main()
